spring.application.name=salaryManagement

# Configuration de la base PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/salary_management
spring.datasource.username=postgres
spring.datasource.password=anjania*98
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port de l'application
server.port=8080

# Configuration de smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malalatianahajaniaina03@gmail.com
spring.mail.password=jugc udzi iaqa fccc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration JWT
jwt.secret-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibm
jwt.expiration=2592000000